### ISSUE TITLE
Document the way to install the CLI on different platform

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamCLI#1]

**Comment by loomis** [comment]
The documentation should include (for each platform):
1. Prerequisites (packages, software, configuration, etc.) before the SlipStream client can be installed.
2. Clear installation instructions, including example commands and responses.
3. Configuration information for the client.
4. Information on how to verify that the client is installed and working correctly. 

The (minimum) platforms that should be documented are:
- [ ] CentOS 7
- [ ] Ubuntu 16.04
- [ ] Ubuntu 14.04
- [ ] Windows 10
- [ ] Mac OS X

Documentation for older versions of these platforms would be useful, but are optional.

The documentation should be part of the standard [SlipStream documentation](http://ssdocs.sixsq.com).

**Comment by mebster** [comment]
Should this not simply be: "pip install slipstream-cli" (or something like that)?

**Comment by mebster** [comment]
If we plan to propose the CLI for HNSciCloud, we need to also have a clear installation procedure.

**Comment by schaubl** [comment]
stale.
